### PR TITLE
add support for web apps to the react-native sdk

### PR DESCRIPTION
**Pull request by gabrielalao**

### CODE REVIEW

**Comment by gabrielalao** [comment]
To run example app as a web app, you could run `npm run web`.

**Comment by tjulien** [comment]
https://app.shortcut.com/radarlabs/story/12310/add-support-for-web-apps-to-the-react-native-sdk

**Review by tjulien — APPROVED** [review]

**Comment by tjulien** [comment]
@gabrielalao looks like there might be a build error: https://app.circleci.com/pipelines/github/radarlabs/react-native-radar/670/workflows/e480fc75-3e60-4505-94aa-b333fa7ea5ac/jobs/1852?invite=true#step-105-1387

**Comment by gabrielalao** [comment]
let me check

**Comment by gabrielalao** [comment]
@tim All are passed now. Could we bump up version & merge & release now?

**Comment by tjulien** [comment]
@gabrielalao Yeah looks good. Does the native Example app still work? If so, can you do a version bump / merge / release?

**Comment by gabrielalao** [comment]
@tim Yes, I already test example app on ios and android as well. All are working well. I will release new version.

**Pull request merged**
