### PR TITLE
allow for Float types in mapToJson

### PR DESCRIPTION
**Pull request by profburial**
see https://github.com/radarlabs/react-native-radar/issues/124

### CODE REVIEW

**Comment by profburial** [comment]
Any hopes of getting some feedback? This is a decent sized bug for anyone using this SDK on android.

**Comment by nickpatrick** [comment]
Hey @profburial, we're cutting a release soon, I can try to get this in. Wondering if there's a more elegant way to do this than calling `toString()`?

**Comment by nickpatrick** [comment]
I'll go ahead and merge this in and make sure it goes out in the next release. Thanks!

**Review by nickpatrick — APPROVED** [review]

**Comment by profburial** [comment]
@nickpatrick thanks for getting this in! I appreciate it!

**Pull request merged**
