### PR TITLE
Track verified changes

### PR DESCRIPTION
**Pull request by york-wei**
- Upgrades Radar Android SDK to `3.9.4`and iOS SDK to `3.9.6`
- Adds a `beacons` param to `Radar.trackVerified()` and `Radar.trackVerifiedToken()` to support beacon ranging.
- Adds `Radar.startTrackingVerified(token, interval, beacons)`, which calls `Radar.trackVerified()` or `Radar.trackVerifiedToken()` every `interval` seconds or on network connection changes and delivers updates to listeners.
- Adds a `token` listener for token updates.

### CODE REVIEW

**Review by lmeier — COMMENTED** [review]
looking good so far.

have you dogfooded this in Waypoint at @york-wei ? Both with `startTrackingVerified`, running this with `beacon: true`, and also listening to the "token" event?

**Comment by york-wei** [comment]
> looking good so far.
> 
> have you dogfooded this in Waypoint at @york-wei ? Both with `startTrackingVerified`, running this with `beacon: true`, and also listening to the "token" event?

verified on waypoint :+1:

**Comment by york-wei** [comment]
Will rebase on Kenny's typescript changes

**Review by KennyHuRadar — CHANGES_REQUESTED** [review]

**Comment by york-wei** [comment]
@KennyHuRadar @lmeier 
iOS: https://expo.dev/accounts/radarlabs/projects/waypoint/builds/3ecc2964-8d75-40db-a71e-29a67fa5b784
Android: https://expo.dev/accounts/radarlabs/projects/waypoint/builds/9d00cb5a-9caa-47a9-82e5-322138dddbf4

**Comment by KennyHuRadar** [comment]
@york-wei tried out the builds on both platforms, `trackVerified` and `trackVerifiedToken` looks good, can you share some QA steps for `startTrackVerified`?

**Comment by york-wei** [comment]
> @york-wei tried out the builds on both platforms, `trackVerified` and `trackVerifiedToken` looks good, can you share some QA steps for `startTrackVerified`?

@KennyHuRadar set  ```
Radar.on('token', (result: string) => {
      console.log('token: ', result);
    });
``` and then call `Radar.startTrackingVerified({
                token: true
              });`

**Comment by KennyHuRadar** [comment]
> > @york-wei tried out the builds on both platforms, `trackVerified` and `trackVerifiedToken` looks good, can you share some QA steps for `startTrackVerified`?
> 
> @KennyHuRadar set `Radar.on('token', (result: string) => { console.log('token: ', result); });` and then call `Radar.startTrackingVerified({ token: true });`

Just tried this and noticed a type error, `Radar.on()` takes in string of the `Event` type, you need to add the string `token` to that enum within the types file.

**Review by KennyHuRadar — APPROVED** [review]
lgtm and I was able to run the new endpoints and callbacks successfully on waypoint, @lmeier would you like to give it a last look before we merge?

**Review by lmeier — APPROVED** [review]
lgtm, well done y'all 🚀

**Pull request merged**
